// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nurbnb.Pagos.Infrastructure.EF.Contexts;

#nullable disable

namespace Nurbnb.Pagos.Infrastructure.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20230808195151_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.CatalogoDevolucionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("catalogoDevolucionId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("NroDias")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nroDias");

                    b.Property<int>("PorcentajeDescuento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("porcentajeDescuento");

                    b.HasKey("Id");

                    b.ToTable("catalogoDevolucion");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.CatalogoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("catalogoId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("EsReserva")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esReserva");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("INTEGER")
                        .HasColumnName("porcentaje");

                    b.HasKey("Id");

                    b.ToTable("catalogo");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.DetallePagoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("detallePagoId");

                    b.Property<Guid>("CatalogoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalogoId");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pagoId");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("INTEGER")
                        .HasColumnName("porcentaje");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("PagoId");

                    b.ToTable("detallePago");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.DevolucionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("devolucionId");

                    b.Property<Guid>("CatalogoDevolucionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalogoDevolucionId");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaRegistro");

                    b.Property<decimal>("ImportePago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importePago");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pagoId");

                    b.Property<int>("PorcentajeDevolucion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("porcentajeDevolucion");

                    b.Property<decimal>("TotalDevolucion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalDevolucion");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoDevolucionId");

                    b.HasIndex("PagoId");

                    b.ToTable("devolucion");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.MedioPagoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("medioPagoId");

                    b.Property<string>("BcoOrigen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("bcoOrigen");

                    b.Property<string>("ComprobanteExterno")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("comprobanteExterno");

                    b.Property<string>("CuentaOrigen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("cuentaOrigen");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pagoId");

                    b.HasKey("Id");

                    b.ToTable("medioPago");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.PagoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("pagoId");

                    b.Property<string>("BcoOrigen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("bcoOrigen");

                    b.Property<decimal>("CostoTotalRenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costoTotalRenta");

                    b.Property<string>("CuentaOrigen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("cuentaOrigen");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaCancelacion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaRegistro");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operacionId");

                    b.Property<int>("TipoPago")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("pago");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.DetallePagoReadModel", b =>
                {
                    b.HasOne("Nurbnb.Pagos.Infrastructure.EF.ReadModel.CatalogoReadModel", "Catalogo")
                        .WithMany()
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nurbnb.Pagos.Infrastructure.EF.ReadModel.PagoReadModel", "Pago")
                        .WithMany("Detalle")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogo");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.DevolucionReadModel", b =>
                {
                    b.HasOne("Nurbnb.Pagos.Infrastructure.EF.ReadModel.CatalogoDevolucionReadModel", "CatalogoDevolucion")
                        .WithMany()
                        .HasForeignKey("CatalogoDevolucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nurbnb.Pagos.Infrastructure.EF.ReadModel.PagoReadModel", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogoDevolucion");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Nurbnb.Pagos.Infrastructure.EF.ReadModel.PagoReadModel", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
